title: Insular
logo: '/assets/images/logo.png'
email: proletarius101@protonmail.com
description: Isolate your big brother
gitlab_username: proletarius101
theme: 'just-the-docs'
baseurl: '/Insular'
kramdown:
  auto_id_prefix: Insular
  auto_id_stripping: false
  auto_ids: true
  entity_output: as_char
  footnote_backlink: '&#8617;'
  footnote_backlink_inline: false
  footnote_nr: 1
  hard_wrap: false
  header_offset: 0
  html_to_native: false
  input: GFM
  line_width: 72
  parse_block_html: false
  parse_span_html: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  show_warnings: true
plugins:
  - jekyll-readme-index
  - jekyll-titles-from-headings
  # - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-relative-links

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Aux links for the upper right navigation
aux_links:
  'Source code on GitLab':
    - '//gitlab.com/secure-system/Insular'
  'Get it on F-Droid':
    - '//f-droid.org/packages/com.oasisfeng.island.fdroid'

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: '%b %e %Y at %I:%M %p' # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true
